language: python
python:
  - "3.5"
install:
  - pip install requests
# command to run tests
script:
import unittest

from repos import repo


class Testrepos(unittest.TestCase):

    def testInvalidRepo1(self):
        self.assertEqual(repo('richkempinski'),[('csp', 2), ('hellogitworld', 30), ('helloworld', 6), ('Mocks', 10), ('Project1', 2), ('richkempinski.github.io', 9), ('threads-of-life', 1), ('try_nbdev', 2), ('try_nbdev2', 5)])

    def testInvalidRepo2(self):
        self.assertEqual(repo('jaitul25'),[('Cloudflare-Jaitul-Bharodiya', 2), ('CS-561-DBMS', 12), ('GithubRepo', 15), ('HW05-Static-Code-Analyzer', 1), ('jaitul25.github.io', 14), ('kg_jaitul25_2021', 5), ('SSW-567', 2), ('Stevens-Database', 3), ('Stevens-Milee-Project', 30), ('Stevens-Web-Solution', 2), ('Triangle567', 11), ('Voyager_SDET_Hiring_Test', 2)])





